name: Deploy para Shopify Development Theme

on:
  push:
    branches:
      - develop

concurrency:
  group: development-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Deploy to Shopify Development Theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: |
          npx @shopify/cli@latest theme push \
          --store ${{ secrets.SHOPIFY_STORE_DOMAIN }} \
          --theme 183862755623 \
          --allow-live
